[package]
name = "dgrlauncher"
version = "0.2.0"
edition = "2024"
authors = ["VLAZOF"]
repository = "https://github.com/VLAZOF/dgrlauncher"
build = "build.rs"

[profile.release]
strip = true
lto = true

[dependencies]
iced = { version = "0.14.0", features = ["tokio", "svg"] }
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
open = "5.4.3"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
image = { version = "0.25", default-features = false, features = ["png"] }
uuid = { version = "1.26.0", default-features = false, features = ["v4", "std"] }
md5 = "0.8.1"
shared_child = "1.1.2"
tar = { version = "0.4.46", default-features = false }
flate2 = { version = "1.1.10", default-features = false, features = ["rust_backend"] }
tokio = { version = "1", features = ["time", "process"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
